use job_e_commerce_platform;

INSERT INTO school (school_name)
VALUES ('Đại học Bách Khoa TP.HCM'),
       ('Đại học Khoa học Tự nhiên TP.HCM'),
       ('Đại học Khoa học Xã hội và Nhân văn TP.HCM'),
       ('Đại học Công nghệ Thông tin TP.HCM'),
       ('Đại học Quốc tế TP.HCM'),
       ('Đại học Kinh tế - Luật TP.HCM'),
       ('Đại học Sư phạm Kỹ thuật TP.HCM'),
       ('Đại học Sư phạm TP.HCM'),
       ('Đại học Y Dược TP.HCM'),
       ('Đại học Ngoại thương - Cơ sở TP.HCM'),
       ('Đại học Ngân hàng TP.HCM'),
       ('Đại học Công nghiệp TP.HCM'),
       ('Đại học Giao thông Vận tải - Cơ sở TP.HCM'),
       ('Đại học Kiến trúc TP.HCM'),
       ('Đại học Văn Lang'),
       ('Đại học Hoa Sen'),
       ('Đại học HUTECH'),
       ('Đại học Nguyễn Tất Thành'),
       ('Đại học Tôn Đức Thắng'),
       ('Đại học FPT TP.HCM');

INSERT INTO major (major_name)
VALUES ('Lập trình viên (Software Developer)'),
       ('Thiết kế đồ họa (Graphic Design)'),
       ('Chỉnh sửa video (Video Editing)'),
       ('Marketing kỹ thuật số (Digital Marketing)'),
       ('SEO & Content Marketing'),
       ('Viết nội dung (Content Writing)'),
       ('Dịch thuật & Biên tập (Translation & Editing)'),
       ('Thiết kế UI/UX'),
       ('Nhiếp ảnh & Chỉnh sửa ảnh (Photography & Photo Editing)'),
       ('Giảng dạy trực tuyến (Online Tutoring)'),
       ('Phát triển Web (Web Development)'),
       ('Phát triển ứng dụng di động (Mobile App Development)'),
       ('Lập trình game (Game Development)'),
       ('Kinh doanh & Tư vấn tài chính cá nhân'),
       ('Hỗ trợ khách hàng từ xa (Remote Customer Support)'),
       ('Quản lý dự án tự do (Freelance Project Management)'),
       ('Âm nhạc & Sản xuất âm thanh (Music & Audio Production)'),
       ('Kỹ thuật viên CAD (CAD Technician)'),
       ('Chuyên gia an ninh mạng (Cybersecurity Specialist)'),
       ('Quay phim & Dựng phim tự do');

INSERT INTO degree (degree_title)
VALUES ('Cử nhân'),
       ('Kỹ sư'),
       ('Thạc sĩ'),
       ('Tiến sĩ'),
       ('Cao đẳng'),
       ('Chứng chỉ');

-- pass 123
INSERT INTO account (email, password, role, created_at, updated_at, status, lat, lng)
VALUES ('tungvtps27852@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'ADMIN', NOW(),
        null, 0, null, null),
       ('quangvdps36680@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER',
        NOW(), null, 0, null, null),
       ('quangbmps28437@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 1, null, null),
       ('tiendqpc07858@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER', NOW(),
        null, 0, null, null),
       ('huydqpc07859@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 0, null, null),
       ('hoanganhps34567@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER',
        NOW(), null, 0, null, null),
       ('minhthanhps12345@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 0, null, null),
       ('ngoclanps56789@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER',
        NOW(), null, 2, null, null),
       ('vietanhps98765@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'ADMIN', NOW(),
        null, 0, null, null),
       ('thanhsonps43210@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 1, null, null),
       ('lananhps88888@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER', NOW(),
        null, 0, null, null),
       ('hoanglongps77777@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 0, null, null),
       ('kimnganps66666@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER',
        NOW(), null, 0, null, null),
       ('minhtrietps55555@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'CLIENT', NOW(),
        null, 1, null, null),
       ('hieunguyenps44444@fpt.edu.vn', '$2a$12$1PUaXLFDOmC4Af926SCOEeCGvOWirieoYIv1Z3L7npEfXYNtF8vjm', 'FREELANCER',
        NOW(), null, 2, null, null);

INSERT INTO users (first_name, last_name, phone_number, province, country, title, introduction, image, account_id)
VALUES ('Tùng', 'Võ', '0976543210', 'Đống Đa', 'Hà Nội', 'Frontend Developer',
        'Chuyên gia ReactJS, VueJS với nhiều dự án UI/UX hiện đại.', 'tungvo.png', 1),
       ('Quang', 'Vũ', '0987654321', 'Tân Phú', 'Hồ Chí Minh', 'Backend Developer',
        'Lập trình viên backend với 3 năm kinh nghiệm trong Java Spring Boot.', 'quangvu.png', 2),
       ('Quang', 'Bùi', '0965432109', 'Bình Thạnh', 'Đà Nẵng', 'CEO', 'Chủ doanh nghiệp công ty công nghệ.',
        'hanguyen.png', 3),
       ('Tiến', 'Đinh', '0954321098', 'Gò Vấp', 'Cần Thơ', 'Digital Marketer',
        'Chuyên gia SEO, quảng cáo Google Ads và Facebook Ads.', 'anhpham.png', 4),
       ('Huy', 'Đinh', '0943210987', 'Gò Vấp', 'Cần Thơ', 'Tech Lead',
        '10 năm kinh nghiệm với vai trò Back-end Development.', 'baole.png', 5),
       ('Hoàng Anh', 'Phạm', '0912345678', 'Cầu Giấy', 'Hà Nội', 'Mobile Developer',
        'Phát triển ứng dụng Android/iOS với Flutter và React Native.', 'hoanganhpham.png', 6),
       ('Minh Thành', 'Nguyễn', '0923456789', 'Thủ Đức', 'Hồ Chí Minh', 'Project Manager',
        'Quản lý và điều phối các dự án phần mềm quy mô lớn.', 'minhthanhnguyen.png', 7),
       ('Ngọc Lan', 'Trần', '0934567890', 'Ninh Kiều', 'Cần Thơ', 'Data Analyst',
        'Phân tích dữ liệu và trực quan hóa với Power BI và Tableau.', 'ngoclantran.png', 8),
       ('Việt Anh', 'Lê', '0945678901', 'Thanh Xuân', 'Hà Nội', 'System Administrator',
        'Quản trị hệ thống mạng, server, bảo mật hạ tầng CNTT.', 'vietanhle.png', 9),
       ('Thành Sơn', 'Đỗ', '0956789012', 'Liên Chiểu', 'Đà Nẵng', 'Business Analyst',
        'Phân tích nghiệp vụ, đưa ra giải pháp cho các hệ thống phần mềm.', 'thanhsondo.png', 10),
       ('Lan Anh', 'Nguyễn', '0901234567', 'Ba Đình', 'Hà Nội', 'Video Editor',
        'Chuyên gia chỉnh sửa video quảng cáo, hậu kỳ chuyên nghiệp cho các sự kiện và phim ngắn.', 'lananhnguyen.png',
        11),
       ('Hoàng Long', 'Trần', '0912345678', 'Quận 1', 'Hồ Chí Minh', 'Agency Manager',
        'Đại diện công ty thiết kế đồ họa, chuyên tìm kiếm đối tác freelancer tài năng.', 'hoanglongtran.png', 12),
       ('Kim Ngân', 'Phạm', '0923456789', 'Nha Trang', 'Khánh Hòa', 'Translator & Editor',
        'Phiên dịch và biên tập viên chuyên nghiệp cho các tài liệu kỹ thuật, pháp lý và sáng tạo.', 'kimnganpham.png',
        13),
       ('Minh Triết', 'Lê', '0934567890', 'Thanh Xuân', 'Hà Nội', 'Studio Owner',
        'Chủ studio chụp ảnh cưới, thời trang và sản phẩm, cần hợp tác với freelancer chỉnh sửa ảnh.',
        'minhtrietle.png', 14),
       ('Hiếu', 'Nguyễn', '0945678901', 'Thủ Dầu Một', 'Bình Dương', 'Online Tutor',
        'Giảng viên trực tuyến, chuyên đào tạo kỹ năng Digital Marketing và Content Writing.', 'hieunguyen.png', 15);

INSERT INTO client (from_price, to_price, type_price, user_id)
VALUES (500000, 2000000, 'VNĐ', 3),
       (1000000, 3000000, 'VNĐ', 5),
       (1500000, 3500000, 'VNĐ', 7),
       (2000000, 5000000, 'VNĐ', 10),
       (2500000, 6000000, 'VNĐ', 12),
       (1800000, 4500000, 'VNĐ', 14);


INSERT INTO company (company_name, phone_contact, address, industry, client_id)
VALUES ('Công ty Công nghệ IBM', '0911001100', 'Đà Nẵng', 'Công nghệ phần mềm', 1),
       ('Công ty Phát triển NVIDIA', '0911002200', 'Cần Thơ', 'Giải pháp phần mềm & Backend', 2),
       ('Tập đoàn Dự án MT', '0911003300', 'Hồ Chí Minh', 'Quản lý dự án CNTT', 3),
       ('Công ty Tư vấn Giải pháp SD', '0911004400', 'Đà Nẵng', 'Tư vấn phân tích nghiệp vụ', 4),
       ('Agency Thiết kế Đồ họa LT', '0911005500', 'Hồ Chí Minh', 'Thiết kế đồ họa & Agency', 5),
       ('Studio Ảnh Minh Triết', '0911006600', 'Hà Nội', 'Studio ảnh cưới và thời trang', 6);

INSERT INTO category (category_title)
VALUES ('Lập trình & Phát triển phần mềm'),
       ('Thiết kế đồ họa & Multimedia'),
       ('Viết lách & Dịch thuật'),
       ('Marketing & Quảng cáo'),
       ('SEO & Phát triển nội dung'),
       ('Dịch vụ khách hàng & Hỗ trợ kỹ thuật'),
       ('Tư vấn kinh doanh & Tài chính'),
       ('Quản lý dự án & Điều hành'),
       ('Sản xuất video & Chỉnh sửa phim'),
       ('Nhập liệu & Hành chính văn phòng');

INSERT INTO skill (skill_name)
VALUES ('Java'),
       ('Spring Boot'),
       ('ReactJS'),
       ('Vue.js'),
       ('Angular'),
       ('Node.js'),
       ('Express.js'),
       ('Python'),
       ('Django'),
       ('Flask'),
       ('Ruby on Rails'),
       ('PHP'),
       ('Laravel'),
       ('C#'),
       ('.NET Core'),
       ('C++'),
       ('Swift'),
       ('Kotlin'),
       ('Flutter'),
       ('React Native'),
       ('SQL'),
       ('MySQL'),
       ('PostgreSQL'),
       ('MongoDB'),
       ('Firebase'),
       ('Data Analysis'),
       ('Data Science'),
       ('Machine Learning'),
       ('Deep Learning'),
       ('TensorFlow'),
       ('PyTorch'),
       ('AWS'),
       ('Azure'),
       ('Google Cloud Platform'),
       ('Docker'),
       ('Kubernetes'),
       ('Jenkins'),
       ('CI/CD Pipelines'),
       ('UI/UX Design'),
       ('Adobe Photoshop'),
       ('Adobe Illustrator'),
       ('Figma'),
       ('Sketch'),
       ('Canva'),
       ('Blender 3D'),
       ('Maya'),
       ('Cinema 4D'),
       ('SEO Optimization'),
       ('Copywriting'),
       ('Content Writing'),
       ('Blog Writing'),
       ('Technical Writing'),
       ('Email Marketing'),
       ('Social Media Marketing'),
       ('Affiliate Marketing'),
       ('Google Ads'),
       ('Facebook Ads'),
       ('TikTok Ads'),
       ('Video Editing'),
       ('Adobe Premiere Pro'),
       ('Final Cut Pro'),
       ('After Effects'),
       ('Animation'),
       ('3D Modeling'),
       ('Music Production'),
       ('Podcast Editing'),
       ('Data Entry'),
       ('Virtual Assistant'),
       ('Project Management'),
       ('Business Consulting'),
       ('Customer Support'),
       ('Sales'),
       ('Lead Generation'),
       ('Accounting'),
       ('Bookkeeping'),
       ('English Translation'),
       ('Chinese Translation'),
       ('Japanese Translation'),
       ('Korean Translation'),
       ('Spanish Translation'),
       ('French Translation'),
       ('German Translation'),
       ('Proofreading'),
       ('Transcription');

INSERT INTO freelancer (hourly_rate, description, category_id, user_id)
VALUES (20.00, 'Backend Developer chuyên về Java Spring Boot, xây dựng API và quản lý cơ sở dữ liệu.', 1, 2),
       (15.00, 'Digital Marketer với chuyên môn SEO, Google Ads và Facebook Ads, giúp tăng trưởng doanh thu.', 4, 4),
       (18.00, 'Mobile Developer chuyên phát triển ứng dụng đa nền tảng với Flutter và React Native.', 1, 6),
       (22.00, 'Data Analyst với kinh nghiệm phân tích và trực quan hóa dữ liệu bằng Power BI và Tableau.', 7, 8),
       (17.00, 'Video Editor chuyên hậu kỳ cho các video sự kiện, quảng cáo và phim ngắn.', 9, 11),
       (14.00, 'Phiên dịch viên và biên tập viên chuyên xử lý tài liệu kỹ thuật và sáng tạo.', 3, 13),
       (16.00, 'Online Tutor chuyên đào tạo kỹ năng viết nội dung chuẩn SEO và Digital Marketing.', 5, 15);

INSERT INTO education (start_date, end_date, description, school_id, degree_id, major_id, freelancer_id, image)
VALUES ('2015-09-01', '2019-06-30', 'Tốt nghiệp loại giỏi chuyên ngành Kỹ thuật phần mềm.', 1, 2, 1, 1, null),
       ('2016-09-01', '2020-06-30', 'Hoàn thành chương trình đào tạo chuyên ngành Marketing kỹ thuật số.', 5, 1, 4, 2,
        null),
       ('2017-09-01', '2021-06-30', 'Nghiên cứu và phát triển các ứng dụng di động trong các dự án sinh viên.', 4, 2,
        12, 3, null),
       ('2014-09-01', '2018-06-30', 'Tốt nghiệp xuất sắc chuyên ngành Phân tích dữ liệu và Khoa học máy tính.', 2, 1, 7,
        4, null),
       ('2015-09-01', '2019-06-30', 'Tham gia nhiều dự án phim ngắn và video quảng cáo cho các câu lạc bộ.', 14, 1, 3,
        5, null),
       ('2013-09-01', '2017-06-30', 'Đào tạo chuyên sâu về Biên - Phiên dịch và Ngôn ngữ học.', 3, 1, 7, 6, null),
       ('2012-09-01', '2016-06-30', 'Đạt chứng chỉ Content Marketing và đào tạo SEO thực chiến.', 16, 6, 5, 7, null);

INSERT INTO job (title, scope, hour_work, duration, job_opportunity, from_price, to_price, type_price, description,
                 type_payment, status, created_at, updated_at, client_id, category_id)
VALUES ('Phát triển Website thương mại điện tử', 'LARGE', 40.00, 60, true, 5000000.00, 15000000.00, 'VNĐ',
        'Cần phát triển một website thương mại điện tử hoàn chỉnh, tích hợp thanh toán online và giao diện thân thiện với người dùng.',
        'FULL', 'OPEN', NOW(), NULL, 1, 1),
       ('Lập trình viên ReactJS hỗ trợ UI/UX', 'MEDIUM', 20.00, 30, false, 3000000.00, 8000000.00, 'VNĐ',
        'Tìm kiếm một lập trình viên ReactJS giúp tối ưu hóa UI/UX cho hệ thống CRM.', 'HOURLY', 'OPEN', NOW(), NULL, 1,
        1),
       ('Backend Developer Java Spring Boot', 'LARGE', 30.00, 90, true, 7000000.00, 20000000.00, 'VNĐ',
        'Cần backend developer có kinh nghiệm với Java Spring Boot, tối ưu hóa hiệu suất và bảo mật.', 'FULL', 'OPEN',
        NOW(), NULL, 2, 1),
       ('Kiểm thử và kiểm tra bảo mật hệ thống backend', 'MEDIUM', 25.00, 45, false, 5000000.00, 12000000.00, 'VNĐ',
        'Cần tester chuyên kiểm tra bảo mật hệ thống và viết báo cáo lỗi chi tiết.', 'HOURLY', 'BANNED', NOW(), NULL, 2,
        1),
       ('Quản lý dự án phần mềm', 'LARGE', 40.00, 120, true, 10000000.00, 25000000.00, 'VNĐ',
        'Tìm kiếm freelancer có kinh nghiệm quản lý dự án Agile/Scrum cho ứng dụng di động.', 'FULL', 'OPEN', NOW(),
        NULL, 3, 8),
       ('Hỗ trợ lập kế hoạch và giám sát tiến độ dự án', 'MEDIUM', 15.00, 30, false, 0.00, 7000000.00, 'VNĐ',
        'Phụ trách lập kế hoạch chi tiết và báo cáo tiến độ cho dự án.', 'HOURLY', 'BANNED', NOW(), NULL, 3, 8),
       ('Phân tích nghiệp vụ hệ thống ERP', 'LARGE', 35.00, 60, true, 8000000.00, 18000000.00, 'VNĐ',
        'Cần BA có kinh nghiệm ERP để tư vấn và phân tích yêu cầu nghiệp vụ.', 'FULL', 'OPEN', NOW(), NULL, 4, 7),
       ('Viết tài liệu SRS và Use Case', 'SMALL', 20.00, 30, false, 5000000.00, 10000000.00, 'VNĐ',
        'Cần người có kinh nghiệm viết tài liệu phân tích nghiệp vụ, SRS và Use Case.', 'HOURLY', 'BANNED', NOW(), NULL,
        4, 7),
       ('Thiết kế logo thương hiệu', 'SMALL', 10.00, 14, false, 2000000.00, 5000000.00, 'VNĐ',
        'Cần freelancer thiết kế logo sáng tạo và chuyên nghiệp cho công ty khởi nghiệp.', 'HOURLY', 'OPEN', NOW(),
        NULL, 5, 2),
       ('Thiết kế giao diện website UX/UI', 'MEDIUM', 30.00, 45, true, 5000000.00, 12000000.00, 'VNĐ',
        'Cần designer có kinh nghiệm thiết kế UX/UI cho ngành thời trang, ưu tiên có portfolio.', 'FULL', 'OPEN', NOW(),
        NULL, 5, 2),
       ('Chỉnh sửa ảnh cưới chuyên nghiệp', 'SMALL', 15.00, 30, true, 3000000.00, 7000000.00, 'VNĐ',
        'Cần freelancer chỉnh sửa ảnh cưới, blend màu sáng tạo theo yêu cầu studio.', 'HOURLY', 'CLOSED', NOW(), NULL,
        6, 9),
       ('Biên tập video highlight đám cưới', 'SMALL', 20.00, 21, false, 4000000.00, 8000000.00, 'VNĐ',
        'Biên tập video cưới, thêm hiệu ứng và âm thanh phù hợp.', 'HOURLY', 'BANNED', NOW(), NULL, 6, 9);



INSERT INTO freelancer_skill (freelancer_id, skill_id)
VALUES (1, 1),
       (1, 2),
       (1, 21),
       (1, 22),
       (2, 48),
       (2, 56),
       (2, 57),
       (2, 50),
       (3, 19),
       (3, 20),
       (4, 26),
       (4, 21),
       (4, 22),
       (5, 59),
       (5, 60),
       (5, 62),
       (6, 76),
       (6, 83),
       (6, 84),
       (7, 50),
       (7, 49),
       (7, 48);

-- Job 1
INSERT INTO job_skill (job_id, skill_id)
VALUES (1, 12),
       (1, 13),
       (1, 21),
       (1, 41),
       (2, 3),
       (2, 41),
       (2, 44),
       (3, 1),
       (3, 2),
       (3, 21),
       (3, 22),
       (3, 33),
       (4, 8),
       (4, 26),
       (5, 71),
       (5, 73),
       (6, 71),
       (6, 69),
       (6, 70),
       (7, 73),
       (7, 26),
       (7, 71),
       (8, 54),
       (8, 73),
       (8, 71),
       (9, 42),
       (9, 43),
       (9, 41),
       (9, 45),
       (10, 41),
       (10, 44),
       (10, 42),
       (10, 3),
       (11, 42),
       (12, 60),
       (12, 61),
       (12, 63);
INSERT INTO cv (title, url, status, freelancer_id)
VALUES
    ('CV Java Developer', 'cv-sample1.pdf', true, 1),
    ('CV Digital Marketing Specialist', 'cv-sample2.pdf', true, 2),
    ('CV Mobile App Developer', 'cv-sample3.pdf', true, 3),
    ('CV Data Analyst', 'cv-sample4.pdf', true, 4),
    ('CV Video Editor Portfolio', 'cv-sample5.pdf', true, 5),
    ('CV Translator & Editor', 'cv-sample6.pdf', true, 6),
    ('CV Content Marketing Tutor', 'cv-sample7.pdf', true, 7),
    ('CV Backend Developer - Spring Boot', 'cv-sample8.pdf', false, 1),
    ('CV Digital Marketing Expert', 'cv-sample9.pdf', false, 2),
    ('CV Flutter Developer', 'cv-sample10.pdf', false, 3),
    ('CV Business Intelligence Analyst', 'cv-sample11.pdf', false, 4),
    ('CV Motion Graphics Specialist', 'cv-sample12.pdf', false, 5),
    ('CV Technical Writer', 'cv-sample13.pdf', false, 6);

INSERT INTO freelancer_review (rating, note)
VALUES
    (4.5, 'Freelancer hoàn thành dự án đúng hạn, chất lượng tốt.'),
    (3.8, 'Cần cải thiện kỹ năng giao tiếp, nhưng chất lượng ổn.');

INSERT INTO client_review (rating, note)
VALUES
    (4.0, 'Client có yêu cầu rõ ràng và thanh toán đúng hạn.'),
    (3.5, 'Dự án có chút thay đổi giữa chừng, nhưng xử lý ổn.');

INSERT INTO freelancer_job (is_saved, status, cv_id, freelancer_id, job_id, freelancer_review_id, client_review_id, applied_date)
VALUES
    (true, 'Applied', 1, 1, 1, NULL, NULL, NOW() - INTERVAL 30 DAY),
    (false, 'InProgress', 2, 2, 2, NULL, NULL, NOW() - INTERVAL 25 DAY),
    (true, 'Completed', 1, 1, 3, 1, 1, NOW() - INTERVAL 90 DAY),
    (false, 'Completed', 2, 2, 4, 2, 2, NOW() - INTERVAL 85 DAY),
    (true, 'Applied', 3, 3, 5, NULL, NULL, NOW() - INTERVAL 20 DAY),
    (false, 'InProgress', 4, 4, 7, NULL, NULL, NOW() - INTERVAL 15 DAY),
    (true, 'Applied', 5, 5, 9, NULL, NULL, NOW() - INTERVAL 10 DAY),
    (false, 'Viewed', 6, 6, 10, NULL, NULL, NOW() - INTERVAL 8 DAY),
    (true, 'Cancelled', 7, 7, 11, NULL, NULL, NOW() - INTERVAL 40 DAY);


INSERT INTO projects (title, tech, description, link, image, freelancer_id)
VALUES ('E-commerce Platform', 'Java, Spring Boot, MySQL', 'Developed a full-featured e-commerce platform with shopping cart, payment integration, and admin dashboard.', 'https://github.com/quangvu/ecommerce', 'project1.jpg', 1),
       ('CRM Dashboard', 'React, Redux, Node.js', 'Created a responsive client management dashboard with analytics and reporting features.', 'https://github.com/quangvu/crm-dashboard', 'project2.jpg', 1),
       ('SEO Campaign Manager', 'Google Analytics, SEMrush', 'Managed SEO campaigns that increased organic traffic by 150% over 6 months.', 'https://digitalmarketer.com/portfolio', 'project3.jpg', 2),
       ('PPC Optimization Tool', 'Google Ads, Python', 'Built a tool to optimize PPC campaigns and reduce cost per acquisition by 35%.', 'https://github.com/tiending/ppc-optimizer', 'project4.jpg', 2),
       ('Mobile Banking App', 'Flutter, Firebase', 'Developed a cross-platform mobile banking application with secure authentication and real-time transactions.', 'https://github.com/hoanganh/bank-app', 'project5.jpg', 3),
       ('Fitness Tracker', 'React Native, GraphQL', 'Created a fitness tracking app with workout plans, progress tracking, and social features.', 'https://github.com/hoanganh/fitness-tracker', 'project6.jpg', 3),
       ('Sales Analytics Dashboard', 'Power BI, SQL', 'Designed an interactive sales analytics dashboard for a retail company.', 'https://ngoclan-analyst.com/portfolio', 'project7.jpg', 4),
       ('Customer Segmentation Model', 'Python, scikit-learn', 'Developed a machine learning model for customer segmentation and targeting.', 'https://github.com/ngoclan/customer-segments', 'project8.jpg', 4),
       ('Wedding Highlight Video', 'Adobe Premiere, After Effects', 'Created a cinematic wedding highlight video with custom animations and effects.', 'https://vimeo.com/lananh/wedding', 'project9.jpg', 5),
       ('Corporate Brand Video', 'Final Cut Pro, DaVinci Resolve', 'Produced a corporate brand video for a tech startup.', 'https://vimeo.com/lananh/techbrand', 'project10.jpg', 5),
       ('Technical Manual Translation', 'CAT Tools, Glossary Management', 'Translated a 200-page technical manual from English to Vietnamese with specialized terminology.', 'https://kimngan-translator.com/portfolio', 'project11.jpg', 6),
       ('Website Localization Project', 'Localization Tools, SEO', 'Managed the localization of an e-commerce website into 5 languages.', 'https://kimngan-translator.com/localization', 'project12.jpg', 6),
       ('Digital Marketing Course', 'Canvas, Zoom', 'Created and delivered a 12-week digital marketing course for beginners.', 'https://hieututors.com/marketing-course', 'project13.jpg', 7),
       ('SEO Fundamentals Workshop', 'SEO Tools, Analytics', 'Conducted workshops on SEO fundamentals for small business owners.', 'https://hieututors.com/seo-workshop', 'project14.jpg', 7);

INSERT INTO experiences (company_name, position, start_date, end_date, description, status, freelancer_id)
VALUES ('FPT Software', 'Java Developer', '2018-06-01', '2020-12-31', 'Developed enterprise applications using Java and Spring Boot. Collaborated in an Agile team environment.', 'VERIFIED', 1),
       ('Nashtech', 'Senior Backend Developer', '2021-01-01', NULL, 'Leading backend development team for financial services applications.', 'VERIFIED', 1),
       ('Digital Agency Vietnam', 'Digital Marketing Specialist', '2019-03-15', '2021-05-30', 'Managed SEO, Google Ads, and Facebook advertising campaigns for clients across various industries.', 'VERIFIED', 2),
       ('Sendo', 'Marketing Analyst', '2021-06-01', NULL, 'Analyzing marketing campaign performance and optimizing digital marketing strategies.', 'VERIFIED', 2),
       ('KMS Technology', 'Mobile Developer', '2018-07-01', '2021-04-30', 'Developed mobile applications using Flutter and React Native for Android and iOS platforms.', 'VERIFIED', 3),
       ('VNG Corporation', 'Senior Mobile Developer', '2021-05-01', NULL, 'Developing and maintaining high-traffic mobile applications with focus on performance optimization.', 'VERIFIED', 3),
       ('Nielsen Vietnam', 'Data Analyst', '2017-09-01', '2020-08-31', 'Conducted market research analysis and created reports for clients in FMCG sector.', 'VERIFIED', 4),
       ('Masan Group', 'Business Intelligence Analyst', '2020-09-01', NULL, 'Developing dashboards and analytics solutions to support business decision-making.', 'VERIFIED', 4),
       ('Yolo Studio', 'Video Editor', '2018-02-15', '2021-01-31', 'Edited wedding and event videos. Created motion graphics and animations for commercial projects.', 'VERIFIED', 5),
       ('VTV Digital', 'Senior Video Producer', '2021-02-01', NULL, 'Producing and editing digital content for multi-platform distribution.', 'VERIFIED', 5),
       ('TransPerfect', 'Translator', '2019-05-01', '2021-03-31', 'Translated technical and marketing documents for international clients.', 'VERIFIED', 6),
       ('Freelance', 'Translator & Editor', '2021-04-01', NULL, 'Providing translation and editing services for technical, legal, and creative content.', 'PENDING', 6),
       ('FPT Education', 'Instructor', '2018-08-01', '2020-12-31', 'Taught digital marketing and content creation courses at FPT Arena.', 'VERIFIED', 7),
       ('Online Education Platform', 'Course Creator & Tutor', '2021-01-01', NULL, 'Creating and delivering online courses in digital marketing and content strategy.', 'PENDING', 7);


SELECT @fj1 := id FROM freelancer_job WHERE freelancer_id = 1 AND job_id = 1 LIMIT 1;
SELECT @fj2 := id FROM freelancer_job WHERE freelancer_id = 2 AND job_id = 2 LIMIT 1;
SELECT @fj3 := id FROM freelancer_job WHERE freelancer_id = 1 AND job_id = 3 LIMIT 1;
SELECT @fj4 := id FROM freelancer_job WHERE freelancer_id = 2 AND job_id = 4 LIMIT 1;
SELECT @fj5 := id FROM freelancer_job WHERE freelancer_id = 3 AND job_id = 5 LIMIT 1;
SELECT @fj6 := id FROM freelancer_job WHERE freelancer_id = 6 AND job_id = 10 LIMIT 1;

INSERT INTO appointments (topic, start_time, duration, description, link, client_id, freelancer_job_id)
VALUES
    ('Phỏng vấn Java Developer', '2023-11-15 10:00:00', 60, 'Phỏng vấn cho vị trí Java Developer, thảo luận về kinh nghiệm Spring Boot và Microservices', 'https://meet.google.com/abc-defg-hij', 1, @fj1),
    ('Thảo luận dự án Digital Marketing', '2023-11-16 14:30:00', 45, 'Thảo luận về chiến lược SEO và PPC cho website thương mại điện tử', 'https://zoom.us/j/12345678', 2, @fj2),
    ('Đánh giá portfolio', '2023-11-17 09:00:00', 90, 'Đánh giá portfolio và thảo luận chi tiết yêu cầu dự án phát triển phần mềm', 'https://teams.microsoft.com/l/meetup-join/19%3a...', 3, @fj3),
    ('Phỏng vấn Data Analyst', '2023-11-18 16:00:00', 60, 'Phỏng vấn cho vị trí Data Analyst, thảo luận về kỹ năng phân tích dữ liệu và trực quan hóa', 'https://meet.google.com/jkl-mnop-qrs', 4, @fj4),
    ('Thảo luận dự án Video Editing', '2023-11-20 11:00:00', 45, 'Thảo luận về yêu cầu và phong cách cho dự án chỉnh sửa video quảng cáo', 'https://zoom.us/j/87654321', 5, @fj5),
    ('Thảo luận dự án dịch thuật', '2023-11-22 13:30:00', 60, 'Thảo luận chi tiết về dự án dịch thuật tài liệu kỹ thuật và deadline', 'https://meet.google.com/stu-vwx-yz', 6, @fj6);

INSERT INTO reported_job (reason_freelancer, reason_admin, description, status, image, created_at, freelancer_id, job_id)
VALUES
    ('Thông tin công việc không chính xác', NULL, 'Mức lương được đăng khác với thỏa thuận thực tế sau khi liên hệ với khách hàng.', 'REPORTED', 'report1.jpg', NOW(), 1, 4),
    ('Khách hàng yêu cầu thêm công việc ngoài phạm vi', NULL, 'Khách hàng liên tục yêu cầu thêm tính năng mà không điều chỉnh ngân sách hoặc thời gian.', 'REPORTED', 'report2.jpg', NOW(), 2, 3),
    ('Khách hàng trễ thanh toán', 'Vi phạm điều khoản thanh toán', 'Khách hàng trễ hạn thanh toán hơn 30 ngày sau khi hoàn thành công việc.', 'RESOLVED', 'report3.jpg', NOW() - INTERVAL 15 DAY, 3, 5),
    ('Công việc vi phạm điều khoản sử dụng', 'Công việc yêu cầu viết nội dung vi phạm bản quyền', 'Khách hàng yêu cầu sao chép nội dung từ các website khác mà không có sự cho phép.', 'IN_PROGRESS', 'report4.jpg', NOW() - INTERVAL 30 DAY, 4, 8),
    ('Quấy rối, giao tiếp không chuyên nghiệp', NULL, 'Khách hàng sử dụng ngôn ngữ thiếu tôn trọng và gây áp lực quá mức.', 'REPORTED', 'report5.jpg', NOW(), 5, 10);